version: '3'

networks:

  frontend:

  backend:


volumes:

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/Desktop/data/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/Desktop/data/mariadb
      o: bind
      type: none


services:

  nginx:
    build: requirements/nginx/
    container_name: nginx
    restart: always
    networks:
      - frontend
    ports:
      - '443:443'
    volumes:
      - 'wordpress:/var/www/html'
    depends_on:
      - wordpress


  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    restart: always
    networks:
      - frontend
      - backend
    #ports:
    #  - '9000:9000'
    volumes:
      - 'wordpress:/var/www/html'
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST:       ${MYSQL_HOST}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
      DOMAIN_NAME:      ${DOMAIN_NAME}
      WP_TITLE:         ${WP_TITLE}
      WP_ADMIN_USR:     ${WP_ADMIN_USR}
      WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
      WP_USR:           ${WP_USR}
      WP_PWD:           ${WP_PWD}
      WP_EMAIL:         ${WP_EMAIL}


  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    networks:
      - backend
    #ports:
    #  - '3306:3306'
    volumes:
      - '../mariadb:/var/www/html'
    environment:
      MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USR:  ${WP_DATABASE_USR}
      WP_DATABASE_PWD:  ${WP_DATABASE_PWD}




