version: "3.5"

networks:
  localhost:
    name: inet

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/tde-nico/data/wordpress
      o: bind
      type: none

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/tde-nico/data/mariadb
      o: bind
      type: none


services:

  nginx:
    depends_on:
      - wordpress
    container_name: nginx_debian
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - localhost
    restart: always
    environment:
      NGINX_C: ${NGINX_C}
      NGINX_ST: ${NGINX_ST}
      NGINX_L: ${NGINX_L}
      NGINX_O: ${NGINX_O}
      NGINX_OU: ${NGINX_OU}
      NGINX_CN: ${NGINX_CN}
      NGINX_EMAIL_ADDRESS: ${NGINX_EMAIL_ADDRESS}

  mariadb:  
    container_name: mariadb_debian
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - localhost
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress_debian
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - localhost
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
